# Generated by Django 5.2.4 on 2025-07-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('capactiy', models.PositiveBigIntegerField(default=0)),
                ('each_person_time', models.PositiveBigIntegerField(default=24)),
                ('active_guests', models.PositiveBigIntegerField(default=0)),
                ('highest_settlement_time', models.PositiveBigIntegerField(default=24)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
