# Generated by Django 5.2.4 on 2025-07-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guests',
            old_name='_id',
            new_name='UID',
        ),
    ]
