# Generated by Django 5.2.4 on 2025-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename__id_guests_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='enter_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
