# Generated by Django 5.2.4 on 2025-07-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_guests_enter_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='from_enter_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
