# Generated by Django 5.2.4 on 2025-07-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_guests_from_enter_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='from_enter_time',
        ),
        migrations.AddField(
            model_name='guests',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
