# Generated by Django 5.2.4 on 2025-07-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_guests_from_enter_time_guests_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='formated_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
