# Generated by Django 5.2.4 on 2025-07-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_guests_formated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='enter_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
