# Generated by Django 5.2.4 on 2025-07-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_guests_enter_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='formated_enter_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
